name: small_faith
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  intl: ^0.20.3
  riverpod: ^3.3.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_hi.png
    - assets/images/dice-1.png
    - assets/images/dice-2.png
    - assets/images/dice-3.png
    - assets/images/dice-4.png
    - assets/images/dice-5.png
    - assets/images/dice-6.png
    - assets/images/samplee.jpg
    - assets/images/hill.jpg
    - assets/svg/googlelogo.svg
    - assets/images/quiz-logo.png
    - assets/svg/bible_icon.svg
    

  fonts:
    - family: Inter
      fonts: 
      - asset: assets/font/Inter_28pt-Regular.ttf
        weight: 400
      - asset: assets/font/Inter_24pt-Bold.ttf
        weight: 700
      - asset: assets/font/Inter_28pt-Black.ttf
        weight: 900
